<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    /**
     * Indicates whether the XSRF-TOKEN cookie should be set on the response.
     *
     * @var bool
     */
    protected $addHttpCookie = true;

    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
 
    protected $except = [
       'utilities/onPermitApplicationSubmit',
       'utilities/onAddUniformApplicantDataset',
       'authentication/onUserLogin',
       'administration/onUserLogOut',
       'tradermanagement/onAccountRegistration',
       'clinicaltrials/saveClinicalTrialApplication',
       'documentmanagement/resumableuploadApplicationDocumentFile',
       'clinicaltrials/saveCtrProgressReportingApplication',
       'clinicaltrials/saveCtrOtherReportingApplication',
       'clinicaltrials/saveCtrSaeReportingApplication',
       'clinicaltrials/onsaveSaeInvestigationsDetails',
       'clinicaltrials/onsaveSuspectedDrugDetails',
       'clinicaltrials/saveClinicalSaeLabTetsDetails',
       'clinicaltrials/saveClinicalSaeDrugsDetails',
      'clinicaltrials/saveClinicalCasualityAssessmentDetails',
       'clinicaltrials/onsaveRelevantHistoryDetails',
       'clinicaltrials/onDeleteMisTablePermitdetails',
       'clinicaltrials/onsaveConcomittantDrugDetails',
       'importexportapp/onAddUniformApplicantDataset',
       'importexportapp/saveDeclarationImportExportApplication',
       'importexportapp/saveBatchProductdetails',
       'importexportapp/savePermitProductdetails',
       'clinicaltrials/onSaveClinicalStudySite',
       'productregistration/onSaveProductApplication',
       'productregistration/onSaveProductQualitySummaryDetails',
       'productregistration/onSaveProductOtherDetails',
       'productregistration/onSaveProductOtherActiveQiSDetails',
       'productregistration/onSaveProductGeneralQiSDetails',
       'productregistration/onSaveProductManufQiSDetails',
       'productregistration/onDeleteProductsDetails',
       'productregistration/onSaveProductQualitySummary',
       'productregistration/onSaveProductCharacterQiSDetails',
      'productregistration/onSaveProductControlAPIQiSDetails',
       'productregistration/onSaveProductReferQiSDetails',
       'clinicaltrials/onsaveclinicaltInvestigatorDetails',
       'clinicaltrials/onsaveclinicaltMonitorDetails',
       'clinicaltrials/saveiMPProductDetailsDetails',
       'clinicaltrials/saveComparatorProductDetailsDetails',
       'importexportapp/saveDisposalApplication',
       'importexportapp/saveDisposalPermitProductdetails',
       'importexportapp/saveControlledDrugsImptPermitApplication',
       'documentmanagement/onunfitProductsUpload',
       'importexportapp/saveRenImportExportApplication',
       'tradermanagement/onUpdateTraderAccountDetails',
       'utilities/onCustomerAccountRegistrationSubmission',
       'utilities/onSaveInspectionDetails',
       'documentmanagement/uploadProductImages',
       'promotionadverts/onSavepromotionalMaterialsDetails',
       'promotionadverts/onDeleteOtherApplicationsDetails',
       'documentmanagement/uploadApplicationDMSDocument',
       'tradermanagement/onPharmacisAccountUsersRegistration',
       'premisesregistration/onSavePremisesApplication',
      'premisesregistration/onSaveDrugShopApplication',
       'premisesregistration/onSavePremisesStoreLocationDetails',
       'importexportapp/saveImportExportApplication',
       'premisesregistration/onSavePremisesDirectors',
       'gmpinspection/onSaveRenewalGmpApplication',
       'premisesregistration/onSaveChangedPharmacistDetails',
       'premisesregistration/onSavePremisesDirectorsDetails',
       'premisesregistration/onSaveProductNotificationApplication',
       'premisesregistration/onSaveNotificationOtherDetails',
       'premisesregistration/onDeletePremisesDetails',
       'premisesregistration/onSavePremisesExternalStore',
       'premisesregistration/onSavePremisesholder',
       'premisesregistration/onSavePremisesPersonnel',
       'importexportapp/onDeletePermitdetails',
       'premisesregistration/onSaveTelephoneDetails',
       'premisesregistration/onSaveRenPremisesApplication',
       'authentication/onFuncChangePassword',
       'utilities/saveManufacturerSiteFulldetails',
       'gmpinspection/onSaveGmpApplication',
      'gmpinspection/onSaveGmpContractDetails',
      'productregistration/onAddManufacturingSite',
      'utilities/onsaveClinicalVariationsrequests',
      'utilities/onApplicationInvoiceGeneration',
      'tradermanagement/onAccountUsersRegistration',
      'clinicaltrials/onSaveClinicalPersonnel',
      'clinicaltrials/onsavePatientInformation',
      'clinicaltrials/saveiMPHandlingProductDetailsDetails',
       'gmpinspection/onSavemanufatcuringSiteBlocks',
       'gmpinspection/onSaveGmpProductLinedetails',
       'gmpinspection/onSaveGmpHistoryInformation',
       'gmpinspection/onSaveIntededmanufatcuringActivity',
       'gmpinspection/onSavePremisesPersonnel',
       'gmpinspection/onDeletePremisesDetails',
       'gmpinspection/onSaveInspectionDetails',
      'gmpinspection/onDeleteMisTablePermitdetails',
       'gmpinspection/onSaveGmpOtherDetails',
       'clinicaltrials/onSaveClincialTrialDescriptionApplication',
       'clinicaltrials/onSaveClincialTrialEthicsApplication',
       'clinicaltrials/onSaveMonitoringApplication',
       'clinicaltrials/onSaveClincialTrialOthersApplication',
       'clinicaltrials/onSaveClincialTrialParticipantsApplication',
       'clinicaltrials/onsaveSummaryActivity',
       'clinicaltrials/onsaveRegulatorystudyLapse',
       'clinicaltrials/onsaveDeviationReport',
       'clinicaltrials/onsaveInspectionReport',
      'clinicaltrials/onSaveClincialTrialHistoryApplication',
      'clinicaltrials/onSaveClincialTrialSummaryApplication',
      'clinicaltrials/onSaveClincialTrialProgressReportApplication',
      'clinicaltrials/onSaveNonClincialTrialToxicology',
       'clinicaltrials/onsaveToxicityDosage',
      'clinicaltrials/onSaveNonClincialTrialPharmacology',
      'clinicaltrials/onSaveClincialTrialMeasures',
      'premisesregistration/onSaveDrugShopStoreLocationDetails',
       'premisesregistration/onSaveApprovalRecomDetails',
       'clinicaltrials/saveAltClinicalTrialApplication',
       'promotionadverts/savePromotionalAdvertapplication',
       'promotionadverts/OnSavePromotionalProductParticulars',
       'utilities/onsaveProductConfigData'
    ];
}
